name: スタック名生成
description: 環境名からCloudFormationスタック名を生成します

inputs:
  environment-name:
    description: '環境名（例: eva, pr-123）'
    required: true

outputs:
  stack-name:
    description: '生成されたスタック名（例: AttendanceKit-Eva-Stack, AttendanceKit-Pr_123-Stack）'
    value: ${{ steps.generate.outputs.stack-name }}

runs:
  using: composite
  steps:
    - name: スタック名の生成
      id: generate
      shell: bash
      run: |
        # 環境名を受け取り、スタック名を生成
        # 1. 最初の文字を大文字化
        # 2. ハイフンをアンダースコアに変換
        # 3. AttendanceKit-{環境名}-Stack の形式で生成
        STACK_NAME="AttendanceKit-$(echo "${{ inputs.environment-name }}" | sed 's/./\U&/' | sed 's/-/_/g')-Stack"
        echo "stack-name=${STACK_NAME}" >> $GITHUB_OUTPUT
        echo "Generated stack name: ${STACK_NAME}"
