name: 'Create Issue on Workflow Failure'
description: 'ワークフロー失敗時にIssueを作成し、Copilotをアサインする'

inputs:
  workflow-name:
    description: 'ワークフロー名'
    required: true
  github-token:
    description: 'GitHub token'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Create Issue on failure
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github-token }}
        WORKFLOW_NAME: ${{ inputs.workflow-name }}
        RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        REPO: ${{ github.repository }}
        COMMIT_SHA: ${{ github.sha }}
      run: |
        ISSUE_BODY=$(cat <<-EOF
        - URL: ${RUN_URL}
        - コミット: ${COMMIT_SHA}

        @copilot workflow-error-handlerスキルでエラー対応してください。
        EOF
        )

        gh issue create \
          --repo "${REPO}" \
          --title "⚠️ ${WORKFLOW_NAME} デプロイエラー" \
          --body "${ISSUE_BODY}" \
          --label "bug,deploy-error" \
          --assignee "copilot" || exit 0
