name: 'Create Issue on Workflow Failure'
description: 'ワークフロー失敗時にIssueを作成し、Copilotをアサインする'

inputs:
  workflow-name:
    description: 'ワークフロー名'
    required: true
  github-token:
    description: 'GitHub token'
    required: true

runs:
  using: "composite"
  steps:
    - name: Create Issue on failure
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github-token }}
        WORKFLOW_NAME: ${{ inputs.workflow-name }}
        RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        REPO: ${{ github.repository }}
        COMMIT_SHA: ${{ github.sha }}
      run: |
        # Issue本文を作成
        ISSUE_BODY=$(cat <<-EOF
        ## ワークフローエラー
        
        ワークフロー **${WORKFLOW_NAME}** が失敗しました。
        
        ### 詳細情報
        
        - **ワークフローURL**: ${RUN_URL}
        - **コミットSHA**: ${COMMIT_SHA}
        - **発生日時**: $(date -u +"%Y-%m-%d %H:%M:%S UTC")
        
        ### 対応依頼
        
        このエラーを調査し、修正を試みてください。
        ワークフローのログを確認して、エラーの原因を特定してください。
        
        ---
        
        @copilot workflow-error-handlerスキルを使用してエラー対応を行ってください。
        EOF
        )

        # Issueを作成（Copilotをアサイン）
        # エラー時は警告を出力して継続（Issue作成失敗でワークフロー全体を失敗させない）
        if ! gh issue create \
          --repo "${REPO}" \
          --title "⚠️ ${WORKFLOW_NAME} デプロイエラー" \
          --body "${ISSUE_BODY}" \
          --label "bug,deploy-error" \
          --assignee "copilot"; then
          echo "⚠️ Warning: Failed to create issue. This might be due to:"
          echo "  - Missing 'issues: write' permission"
          echo "  - Missing 'bug' or 'deploy-error' labels"
          echo "  - User 'copilot' does not exist or does not have access"
          exit 0  # Issue作成失敗でもワークフローは継続
        fi
        
        echo "✅ Issue created successfully"
