name: premerge-check
description: |
  プレマージワークフローをローカルで実行してCI/CDチェックを行います。
  GitHub ActionsのPremergeワークフロー（lint、test、build）をローカル環境で検証できます。
  
  このスキルは以下の場合に使用します:
  - プルリクエストを作成する前にCI/CDチェックを実行したい
  - ローカルでワークフローの動作を確認したい
  - デバッグやトラブルシューティングを行いたい

instructions: |
  このスキルは `npm run premerge:local` コマンドを実行して、
  .github/workflows/premerge.yml で定義されたワークフローをローカルで実行します。
  
  実行される内容:
  1. コードのチェックアウト
  2. Node.js 22のセットアップ
  3. 依存関係のインストール (npm ci)
  4. Lintチェック (npm run lint)
  5. テスト実行 (npm test)
  6. ビルド実行 (npm run build)
  
  使用方法:
  ```bash
  npm run premerge:local
  ```
  
  前提条件:
  - Dockerが起動していること
  - actツールがインストールされていること（インストール手順はscripts/README.mdを参照）
  
  トラブルシューティング:
  - SSL証明書エラーが発生する場合は、ローカルのNode.jsで直接コマンドを実行できます
  - 詳細なトラブルシューティング情報は scripts/README.md を参照してください

examples:
  - description: プレマージチェックを実行
    command: npm run premerge:local
  
  - description: SSL証明書エラーが発生する場合の代替方法
    command: |
      npm ci
      npm run lint
      npm test
      npm run build

metadata:
  category: ci-cd
  tags:
    - premerge
    - github-actions
    - ci
    - testing
    - local-execution
  version: 1.0.0
  author: GitHub Copilot Agent
  created: 2026-01-10
  
references:
  - title: スクリプト使用方法
    path: scripts/README.md
  - title: プレマージワークフロー定義
    path: .github/workflows/premerge.yml
  - title: act - GitHub Actions local runner
    url: https://github.com/nektos/act
