name: 'Comment on Workflow Failure'
description: 'ワークフロー失敗時にPRにコメントし、同じワークフローの過去のコメントを削除する'

inputs:
  workflow-name:
    description: 'ワークフロー名（コメント識別用）'
    required: true
  failure-message:
    description: '失敗メッセージ'
    required: true
  github-token:
    description: 'GitHub token'
    required: true

runs:
  using: "composite"
  steps:
    - name: Post or update failure comment
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        header: workflow-failure-${{ inputs.workflow-name }}
        message: |
          ## ❌ ${{ inputs.workflow-name }} 失敗
          
          ${{ inputs.failure-message }}
          
          [実行ログ](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
        GITHUB_TOKEN: ${{ inputs.github-token }}
