name: 'Start Agent Task on Deploy Failure'
description: 'デプロイワークフロー失敗時にCopilot Agentタスクを開始する'

inputs:
  workflow-name:
    description: 'ワークフロー名'
    required: true
  github-token:
    description: 'GitHub token'
    required: true

runs:
  using: "composite"
  steps:
    - name: Start Copilot Agent Task on failure
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github-token }}
        WORKFLOW_NAME: ${{ inputs.workflow-name }}
        RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        REPO: ${{ github.repository }}
      run: |
        TASK_DESCRIPTION="ワークフロー ${WORKFLOW_NAME} が失敗しました。workflow-error-handler スキルを使用してエラー対応してください。

        URL: ${RUN_URL}"
        
        echo "${TASK_DESCRIPTION}" | gh agent-task create -F - --repo ${REPO}
