name: 'Commit and Comment'
description: '変更をコミットし、PRにコメントを投稿する再利用可能なアクション'

inputs:
  files:
    description: 'コミット対象のファイルパス'
    required: true
  commit-message:
    description: 'コミットメッセージ'
    required: true
  pr-comment:
    description: 'PRに投稿するコメント（変更がある場合のみ）'
    required: true
  github-token:
    description: 'GitHub token'
    required: true

runs:
  using: "composite"
  steps:
    - name: Check for changes
      id: check-changes
      shell: bash
      run: |
        # ファイルパターンを改行区切りで処理
        has_changes=false
        while IFS= read -r pattern; do
          # 空行をスキップ
          if [[ -z "$pattern" ]]; then
            continue
          fi
          # 各パターンについて変更をチェック
          if ! git diff --quiet -- "$pattern" 2>/dev/null; then
            has_changes=true
            break
          fi
        done <<< "${{ inputs.files }}"
        
        if [[ "$has_changes" == "true" ]]; then
          echo "has_changes=true" >> $GITHUB_OUTPUT
          echo "Changes detected"
        else
          echo "has_changes=false" >> $GITHUB_OUTPUT
          echo "No changes detected"
        fi

    - name: Commit and push changes
      id: commit-changes
      if: steps.check-changes.outputs.has_changes == 'true'
      shell: bash
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        
        # ファイルパターンを改行区切りで処理してgit addを実行
        while IFS= read -r pattern; do
          # 空行をスキップ
          if [[ -z "$pattern" ]]; then
            continue
          fi
          # 各パターンを個別にgit add
          git add -- "$pattern" 2>/dev/null || true
        done <<< "${{ inputs.files }}"
        
        # 変更がステージングされているか確認
        if git diff --cached --quiet; then
          echo "No changes staged, skipping commit"
          echo "committed=false" >> $GITHUB_OUTPUT
          exit 0
        fi
        
        git commit -m "${{ inputs.commit-message }}"
        git push
        echo "committed=true" >> $GITHUB_OUTPUT

    - name: Comment on PR
      if: steps.commit-changes.outputs.committed == 'true'
      uses: actions/github-script@v7
      with:
        github-token: ${{ inputs.github-token }}
        script: |
          const commits = await github.rest.repos.listCommits({
            owner: context.repo.owner,
            repo: context.repo.repo,
            sha: context.sha,
            per_page: 1
          });
          const commitUrl = commits.data[0].html_url;
          const commitSha = commits.data[0].sha.substring(0, 7);
          
          const comment = `${{ inputs.pr-comment }}\n\n変更: [${commitSha}](${commitUrl})`;

          await github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
            body: comment
          });
